/*
* COPYRIGHT © 2024 RIBBON COMMUNICATIONS OPERATING COMPANY, INC. ALL RIGHTS RESERVED.
* This publication and the information contained herein is the property of Ribbon
* and may not be copied, reproduced or distributed in any form or by any means without
* the prior written permission of Ribbon.
*
* THIS PUBLICATION IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
* PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
* FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
* OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE PUBLICATION OR ITS USE.
*
* SMCameraModes.h
*
* @version: 6.34.0
*
*/

/**
 * @brief enum class for Camera Modes
 *
 * - CAMERA_ORIENTATION_USES_NONE,
 * - CAMERA_ORIENTATION_USES_DEVICE,
 * - CAMERA_ORIENTATION_USES_STATUS_BAR
 *
 * @since 2.0.0
 */

#ifndef MobileSDK_CameraModes_h
#define MobileSDK_CameraModes_h

typedef NS_ENUM(NSInteger, SMCameraOrientationMode) {
    
    /** CAMERA ORIENTATION USES NONE */
    CAMERA_ORIENTATION_USES_NONE NS_SWIFT_NAME(none),
    
    /** CAMERA ORIENTATION USES DEVICE */
    CAMERA_ORIENTATION_USES_DEVICE NS_SWIFT_NAME(device),
    
    /** CAMERA ORIENTATION USES STATUS BAR */
    CAMERA_ORIENTATION_USES_STATUS_BAR NS_SWIFT_NAME(statusBar)
};

#endif
